In [1]:
# code from: https://pennylane.ai/qml/demos/quantum_neural_net.html

In [1]:
import pennylane as qml
from pennylane import numpy as np
from pennylane.optimize import AdamOptimizer

In [2]:
dev = qml.device("strawberryfields.fock", wires=1, cutoff_dim=10)

In [3]:
def layer(v):
    # Matrix multiplication of input layer
    qml.Rotation(v[0], wires=0)
    qml.Squeezing(v[1], 0.0, wires=0)
    qml.Rotation(v[2], wires=0)

    # Bias
    qml.Displacement(v[3], 0.0, wires=0)

    # Element-wise nonlinear transformation
    qml.Kerr(v[4], wires=0)
    

In [4]:
@qml.qnode(dev)
def quantum_neural_net(var, x=None):
    # Encode input x into quantum state
    qml.Displacement(x, 0.0, wires=0)

    # "layer" subcircuits
    for v in var:
        layer(v)
    print('s')
    return qml.expval(qml.X(wires=0))

In [5]:
def square_loss(labels, predictions):
    loss = 0
    for l, p in zip(labels, predictions):
        loss = loss + (l - p) ** 2

    loss = loss / len(labels)
    return loss

In [6]:
def cost(var, features, labels):
    preds = [quantum_neural_net(var, x=x) for x in features]
    return square_loss(labels, preds)

In [7]:
data = np.loadtxt("sine.txt")
X = data[:, 0]
Y = data[:, 1]

In [8]:
import matplotlib.pyplot as plt

plt.figure()
plt.scatter(X, Y)
plt.xlabel("x", fontsize=18)
plt.ylabel("f(x)", fontsize=18)
plt.tick_params(axis="both", which="major", labelsize=16)
plt.tick_params(axis="both", which="minor", labelsize=16)
plt.show()

<Figure size 640x480 with 1 Axes>

In [9]:
np.random.seed(0)
num_layers = 4
var_init = 0.05 * np.random.randn(num_layers, 5)
print(type(var_init))

<class 'pennylane.numpy.tensor.tensor'>


In [10]:
opt = AdamOptimizer(0.01, beta1=0.9, beta2=0.999)

var = var_init
print(var)
for it in range(500):
    var = opt.step(cost(var,X,Y))
    print("Iter: {:5d} | Cost: {:0.7f} ".format(it + 1, cost(var, X, Y)))

[[ 0.08820262  0.02000786  0.0489369   0.11204466  0.0933779 ]
 [-0.04886389  0.04750442 -0.00756786 -0.00516094  0.02052993]
 [ 0.00720218  0.07271368  0.03805189  0.00608375  0.02219316]
 [ 0.01668372  0.07470395 -0.01025791  0.01565339 -0.04270479]]
s


TypeError: tuple indices must be integers or slices, not Wires

In [84]:
var =([[0.2,0.2,0.2,0.2,0.2],
     [0.2,0.2,0.2,0.2,0.2],
     [0.2,0.2,0.2,0.2,0.2],
     [0.2,0.2,0.2,0.2,0.2],
     [0.2,0.2,0.2,0.2,0.2]])

quantum_neural_net(var, x=1)
layer(var[0])

x
x
x
x
x
s


TypeError: tuple indices must be integers or slices, not Wires